version: "3.9"  # optional since v1.27.0
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: