app:
  key: bp
  name: blueprint
spring:
  profiles:
    active: local
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: test
      authentication-database: admin
  security:
    user:
      name: local
      password: local
server:
  port: 8080
  session:
    timeout: 600
springdoc:
  swagger-ui:
    path: /openapi/ui
  api-docs:
    path: /openapi
