app:
  key: bp
  name: blueprint
spring:
  profiles:
    active: local
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: test
      authentication-database: admin
server:
  port: 8080
  session:
    timeout: 600